service: aws-sentiment-analysis

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2  # Amazon Linux 2 사용
  region: ap-northeast-2
  ecr:
    images:
      appimage:
        uri: 851725622904.dkr.ecr.ap-northeast-2.amazonaws.com/aws-sentiment-analysis:latest

functions:
  app:
    image:
      name: appimage
    memorySize: 2048  # 메모리 크기를 2048MB로 설정
    timeout: 120  # 타임아웃을 60초로 설정
    environment:
      HF_HOME: /tmp  # Hugging Face 캐시 디렉토리를 /tmp로 설정
    events:
      - httpApi: '*'